# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "bento/centos-7.6"
  config.vm.box_version = "201812.27.0"

  # Fixes changes from https://github.com/mitchellh/vagrant/pull/4707
  config.ssh.insert_key = false

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  # CentOS 7.0 x86_64
  #config.vm.box_url = "http://cloud.terry.im/vagrant/oraclelinux-7-x86_64.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048] # RAM allocated to each VM
  end

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.define :c7601 do |c7601|
    # uncomment the line below to set up the ambari dev environment
    # c7601.vm.provision :shell, :path => "dev-bootstrap.sh"
    c7601.vm.hostname = "c7601.ambari.apache.org"
    c7601.vm.network :private_network, ip: "192.168.76.101"
    c7601.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 4096] # RAM allocated to each VM
    end
  end

  config.vm.define :c7602 do |c7602|
    c7602.vm.hostname = "c7602.ambari.apache.org"
    c7602.vm.network :private_network, ip: "192.168.76.102"
  end

  config.vm.define :c7603 do |c7603|
    c7603.vm.hostname = "c7603.ambari.apache.org"
    c7603.vm.network :private_network, ip: "192.168.76.103"
  end

#  config.vm.define :c7604 do |c7604|
#    c7604.vm.hostname = "c7604.ambari.apache.org"
#    c7604.vm.network :private_network, ip: "192.168.76.104"
#  end
#
#  config.vm.define :c7605 do |c7605|
#    c7605.vm.hostname = "c7605.ambari.apache.org"
#    c7605.vm.network :private_network, ip: "192.168.76.105"
#  end
#
#  config.vm.define :c7606 do |c7606|
#    c7606.vm.hostname = "c7606.ambari.apache.org"
#    c7606.vm.network :private_network, ip: "192.168.76.106"
#  end
#
#  config.vm.define :c7607 do |c7607|
#    c7607.vm.hostname = "c7607.ambari.apache.org"
#    c7607.vm.network :private_network, ip: "192.168.76.107"
#  end
#
#  config.vm.define :c7608 do |c7608|
#    c7608.vm.hostname = "c7608.ambari.apache.org"
#    c7608.vm.network :private_network, ip: "192.168.76.108"
#  end
#
#  config.vm.define :c7609 do |c7609|
#    c7609.vm.hostname = "c7609.ambari.apache.org"
#    c7609.vm.network :private_network, ip: "192.168.76.109"
#  end
#
#  config.vm.define :c7610 do |c7610|
#    c7610.vm.hostname = "c7610.ambari.apache.org"
#    c7610.vm.network :private_network, ip: "192.168.76.110"
#  end













  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file precise32.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "init.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
